version: "2.2"
services:
  server:
    build: . #Build image from source repository
    container_name: evemu_server
    volumes:
      - config:/app/etc
      - server_cache:/app/server_cache
      - image_cache:/app/image_cache
    ports:
      - "26000:26000"
      - "26001:26001"
    depends_on:
      - db
    links:
      - "db"
    environment:
      - SEED_MARKET=FALSE # Set to TRUE to seed the market when the server starts for the first time
      - SEED_SATURATION=80 # Set saturation level of seed
      - SEED_REGIONS=Derelik,The Citadel,The Forge # Define regions to be seeded
      - RUN_WITH_GDB=FALSE #Set to TRUE to run evemu with gdb automatically
    stdin_open: true # Enables stdin for the container. Attach to it with 'docker attach'
    tty: true
    cap_add: #This is required for gdb to work
      - SYS_PTRACE

  db:
    image: "bitnami/mariadb:10.4"
    container_name: evemu_db
    volumes:
      - db:/bitnami/mariadb
    # If you want to connect to the Database pick your host port to map it to, (host-port:container-port) below. 
    #ports:
    #  - "3306:3306"  
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=evemu
      - MARIADB_PASSWORD=evemu
      - MARIADB_DATABASE=evemu
volumes:
  db:
  config:
  server_cache:
  image_cache:

